backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

local_backend: true
locale: 'customFr'

site_url: 'https://sfpr.netlify.app'
media_folder: static/img
public_folder: /img

# DEFINITIONS
definitions:
  markdown: &markdown
    widget: 'markdown'
    buttons:
      - 'bold'
      - 'italic'
      - 'link'
      - 'heading-one'
      - 'heading-two'
      - 'heading-three'
      - 'quote'
      - 'bulleted-list'
      - 'numbered-list'
    editorComponents:
      - 'image'

collections:
  # PERSONAL COLLECTIONS
  - name: 'page'
    label: 'Pages'
    label_singular: 'Page'
    description: "Les pages de SFPR. Il est seulement possible de modifier leur contenu, pas d'en créer de nouvelles."
    preview_path: '{{slug}}'
    # editor:
    #   preview: false
    files:
      # HOME - Home page of SFPR
      - name: 'home'
        label: "Page d'accueil"
        file: 'src/pages/index.md'
        fields:
          - name: 'title'
            label: 'Titre du site'
            widget: 'string'
          - name: 'intro'
            label: 'Introduction'
            widget: 'text'
          - name: 'featured_article'
            label: 'Article mis en avant'
            required: false
            widget: 'relation'
            collection: 'article'
            searchFields:
              - 'title'
            valueField: 'title'

      # ABOUT US - The page describing the SFPR team
      - name: 'about-us'
        label: 'Qui sommes-nous ?'
        file: 'src/pages/about-us.md'
        fields:
          - name: 'title'
            label: 'Titre'
            widget: 'string'
          - name: 'body'
            label: 'Corps de texte'
            <<: *markdown
          - name: 'administrators'
            label: 'Membres du bureau'
            widget: 'string'
            hint: 'Sous-titre de la section "Membres du bureau"'
          - name: 'founders'
            label: 'Membres fondateurs'
            widget: 'string'
            hint: 'Sous-titre de la section "Membres fondateurs"'
          - name: 'members'
            label: 'Sociétaires'
            widget: 'string'
            hint: 'Sous-titre de la section "Sociétaires"'

      # NEWS - The page including the news of SFPR
      - name: 'news'
        label: 'Vie de la société'
        file: 'src/pages/news.md'
        fields:
          - label: 'Titre'
            name: 'title'
            widget: 'string'
          - label: 'Corps de texte'
            name: 'body'
            <<: *markdown

      # PUBLICATIONS - The page including the publications of SFPR members
      - name: 'publications'
        label: 'Publications'
        file: 'src/pages/publications.md'
        fields:
          - label: 'Titre'
            name: 'title'
            widget: 'string'
          - label: 'Corps de texte'
            name: 'body'
            <<: *markdown

      # EVENTS - The page including the events of SFPR
      - label: 'Évènements'
        name: 'events'
        file: 'src/pages/events.md'
        fields:
          - label: 'Titre'
            name: 'title'
            widget: 'string'
          - label: 'Corps de texte'
            name: 'body'
            <<: *markdown

      # BLOGS - The page including the blogs articles of SFPR
      - label: 'Articles de blog'
        name: 'blogs'
        file: 'src/pages/blogs.md'
        fields:
          - label: 'Titre'
            name: 'title'
            widget: 'string'
          - label: 'Corps de texte'
            name: 'body'
            <<: *markdown
      # SEARCH - The search page
      # - label: 'Rechercher'
      #   name: 'search'
      #   file: 'assets/content/pages/search.json'
      #   fields:
      #     - label: 'Titre'
      #       name: 'title'
      #       widget: 'string'
      #     - label: 'Nom du champ de recherche'
      #       name: 'input_label'
      #       widget: 'string'

  # BLOGS - A blog
  - name: 'blog'
    label: 'Blogs'
    label_singular: 'Blog'
    description: 'Les blogs publiés sur le site.'
    folder: 'src/pages/blogs'
    create: true
    slug: '{{fields.date}}-{{fields.author}}-{{slug}}'
    summary: 'Le {{month}}/{{year}} par {{fields.author}} : {{fields.title}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'blog',
        }
      - label: 'Auteur'
        name: 'author'
        widget: 'relation'
        collection: 'member'
        searchFields:
          - 'firstName'
          - 'lastName'
        displayFields:
          - '{{firstName}} {{lastName}}'
        valueField: '{{slug}}'
      - label: 'Titre'
        name: 'title'
        widget: 'string'
      - label: 'Corps de texte'
        name: 'body'
        <<: *markdown
      - label: 'Date de publication'
        name: 'date'
        widget: 'datetime'
        format: 'YYYY-MM-DD'
        dateFormat: 'DD/MM/YYYY'
        timeFormat: false
        hint: "La date de publication influe sur l'odre d'affichage des blogs."

  # ARTICLES - An article
  - name: 'article'
    label: 'Articles'
    label_singular: 'Article'
    description: 'Les articles publiés sur le site.'
    folder: 'src/pages/articles'
    sortableFields: ['date', 'title']
    create: true
    slug: '{{fields.date}}-{{slug}}'
    preview_path: 'articles/{{slug}}'
    summary: '{{month}}/{{year}} - {{fields.title}}'
    # editor:
    #   preview: false
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'article',
        }
      - label: 'Titre'
        name: 'title'
        widget: 'string'
      - label: 'Type'
        name: 'type'
        widget: 'select'
        options:
          - label: 'Événements'
            value: 'event'
          - label: 'Publications'
            value: 'publication'
          - label: 'Vie de la société'
            value: 'news'
          - label: 'Article de blog'
            value: 'blog'
      - label: 'Illustration principale'
        name: 'picture'
        widget: 'object'
        fields:
          - label: 'Image'
            name: 'src'
            widget: 'image'
            required: false
          - label: 'Affichage'
            name: 'display'
            widget: 'select'
            default: 'embed'
            multiple: false
            hint: "Un bandeau s'affichera en pleine page, et ses bords peuvent être rognés. Un médaillon (comme une couverture de livre) sera plus petit et ne sera jamais rogné."
            options:
              - label: 'Médaillon'
                value: 'embed'
              - label: 'Bandeau'
                value: 'cover'
      - label: 'Corps de texte'
        name: 'body'
        <<: *markdown
      - label: 'Date de publication'
        name: 'date'
        widget: 'datetime'
        format: 'YYYY-MM-DD'
        dateFormat: 'DD/MM/YYYY'
        timeFormat: false
        hint: "La date de publication influe sur l'odre d'affichage des articles. Vous pouvez indiquer aujourd'hui, ou une date dans le passé."
      - label: 'Options'
        name: 'settings'
        widget: 'object'
        collapsed: true
        fields:
          - label: 'Invisible'
            name: 'hidden'
            widget: 'boolean'
            hint: "Si vous cochez cette case, l'article ne s'affichera pas sur le site internet."
            default: false
          - label: 'Description courte'
            name: 'description'
            widget: 'text'
            required: false
            hint: "Si vous choisissez de remplir ce texte, il s'affichera comme résumé de l'article (sinon, le début de l'article sera utilisé)."

  # MEMBERS - A member of SFPR
  - name: 'member'
    label: 'Sociétaires'
    label_singular: 'Sociétaire'
    description: 'La liste des sociétaires de la SFPR'
    identifier_field: 'lastName'
    sortableFields: ['firstName', 'lastName']
    # format: 'json'
    folder: 'src/content/members'
    create: true
    slug: '{{fields.firstName}}-{{fields.lastName}}'
    summary: '{{fields.firstName}} {{fields.lastName}}'
    preview_path: 'about-us'
    editor:
      preview: false
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'member',
        }
      - name: 'firstName'
        label: 'Prénom'
        widget: 'string'
      - name: 'lastName'
        label: 'Nom de famille'
        widget: 'string'
      - name: 'portrait'
        label: 'Photo'
        widget: 'image'
        required: false
        hint: 'Le visage de la personne doit être (approximativement) au centre de la photo.'
      - name: 'roles'
        label: 'Statut'
        widget: 'select'
        multiple: true
        required: false
        options:
          - label: 'Membre fondateur'
            value: 'FOUNDER'
          - label: 'Membre du bureau'
            value: 'ADMINISTRATOR'
      - name: 'job'
        label: 'Poste actuel dans la SFPR'
        widget: 'string'
        required: false
      - name: 'website'
        label: 'Site internet'
        widget: 'string'
        required: false
        hint: 'Le lien vers la page internet de cette personne.'
